### ISSUE TITLE
They modified BFBD library

### ISSUE THREAD

**Issue by xAstroBoy** [thunderstorm010/ShowHiddenChannels#1]
Modified BFBD library to break the plugin completely.

![image](https://user-images.githubusercontent.com/92211398/188452099-5b3f39b1-7c7a-4d81-82a9-fb340d13d5a6.png)

**Comment by thunderstorm010** [comment]
Hmm, let me try to upload a working version of BDFDB

**Comment by xAstroBoy** [comment]
Also i suggest changing the name a bit because they made BD update the plugin regardless automatically.

**Comment by thunderstorm010** [comment]
solved for now

**Comment by xAstroBoy** [comment]
Nope, is not the correct one
https://github.com/mwittrien/BetterDiscordAddons/commit/3119526904e3e4954d5441fad3ad97a31a102e56
this is the correct PR, we need to update both files.

**Comment by thunderstorm010** [comment]
it works! 😃

**Comment by tryoutuser** [comment]
@thunderstorm010 i am sorry being off topic but thank you very much for your fork! this plugin has been very useful despite we can't even see channel contents. dumbass pepega shit betterdiscord guidelines
