### ISSUE TITLE
Forced update 

### ISSUE THREAD

**Issue by xAstroBoy** [thunderstorm010/ShowHiddenChannels#2]
It forces update, we need to kill the forced updating system or rename the plugin & lib to not force update anymore

**Comment by thunderstorm010** [comment]
can't reproduce i've already fixed update links

**Comment by xAstroBoy** [comment]
There's two more urls that get the original library in the BDFD plugin, replace those two.

**Comment by xAstroBoy** [comment]
There we go <3
