### ISSUE TITLE
This plugin  is in violation of the BetterDiscord plugin guidelines

### ISSUE THREAD

**Issue by Ruthenic** [thunderstorm010/ShowHiddenChannels#4]
I will be sending my lawyers.

**Comment by Iucism** [comment]
🤓

**Comment by thunderstorm010** [comment]
Unfortunately, I do not care.

**Comment by TollyH** [comment]
And BetterDiscord is in violation of the Discord TOS, what's your point? ¯\\\_(ツ)\_/¯
