### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by CanadaHonk** [thunderstorm010/ShowHiddenChannels#5]
You're breaking the terms of the GPL2 license [included in the repo](https://github.com/mwittrien/BetterDiscordAddons/blob/master/LICENSE). Please don't, it's not very cool.

**Comment by NefariousIntent2** [comment]
Absolutely agreed. DevilBro can easily shut this repo down. Thats what I advise him to do.

**Comment by CanadaHonk** [comment]
No, you need to also follow all the terms in the license, like stating changes and disclosing the original source.

**Comment by thunderstorm010** [comment]
Is it fixed?

**Comment by CanadaHonk** [comment]
I guess so.
