### ISSUE TITLE
It still auto-deletes itself

### ISSUE THREAD

**Issue by teisseire117** [thunderstorm010/ShowHiddenChannels#8]
I stopped Discord,
downloaded the archive from your github,
dropped both `0BDFDB.plugin.js` and `ShowHiddenChannels.plugin.js` files into my `C:\Users\<USER>\AppData\Roaming\BetterDiscord\plugins` folder,
then I launched Discord

And it still shows : 
![unPGfCt](https://user-images.githubusercontent.com/43145883/188483040-bfbb2a03-0a6e-4ab4-aefb-fb4b9df3004d.png)

Am I doing something wrong ?

**Comment by thunderstorm010** [comment]
Let me try to reproduce

**Comment by mutageneral** [comment]
![image](https://user-images.githubusercontent.com/62779748/188484391-61746ad0-7747-4cd6-8e0b-6679a219eb42.png)
You are going to have to find a brand-new name for the plugin, change all the metadata.
You should also do the same with the 0BDFDB lib as it would let you use this add-on at the same time as others normal add-ons that needs newest version of 0BDFDB.

**Comment by xAstroBoy** [comment]
see #9 for fix

**Comment by teisseire117** [comment]
> see #9 for fix

It seems to work, despite it showing 
![6CbPfqU](https://user-images.githubusercontent.com/43145883/188486688-4f55eefa-dd49-4b00-8363-2580e530813a.png)
on every reload

**Comment by darbdarb** [comment]
i cant see any hidden channels with this i get the error above ^, and im going to discords i know have hidden channels and nothing

**Comment by BlackLightX** [comment]
> > see #9 for fix
> 
> It seems to work, despite it showing ![6CbPfqU](https://user-images.githubusercontent.com/43145883/188486688-4f55eefa-dd49-4b00-8363-2580e530813a.png) on every reload
I get the notification in the screenshot, but I can't see the hidden channels, so it doesn't work.

**Comment by xAstroBoy** [comment]
The guide is , yall have to replace the entire BDFD files, and put the modified ones, not the plugin alone.

**Comment by thunderstorm010** [comment]
> > > see #9 for fix
> > 
> > 
> > It seems to work, despite it showing ![6CbPfqU](https://user-images.githubusercontent.com/43145883/188486688-4f55eefa-dd49-4b00-8363-2580e530813a.png) on every reload
> 
> I get the notification in the screenshot, but I can't see the hidden channels, so it doesn't work.
I'm trying to fix this but no luck so far

**Comment by teisseire117** [comment]
> > > see #9 for fix
> > 
> > 
> > It seems to work, despite it showing ![6CbPfqU](https://user-images.githubusercontent.com/43145883/188486688-4f55eefa-dd49-4b00-8363-2580e530813a.png) on every reload
> 
> I get the notification in the screenshot, but I can't see the hidden channels, so it doesn't work.

It only show Hidden voice channels you're right

**Comment by xAstroBoy** [comment]
Please screenshot what the inspector console says about showhiddenchannel

**Comment by thunderstorm010** [comment]
Could you try again with the latest commit?

**Comment by darbdarb** [comment]
> Could you try again with the latest commit?

this seems to have fixed it and now shows channels and voice

**Comment by teisseire117** [comment]
> Could you try again with the latest commit?

fixed, thanks

**Comment by mutageneral** [comment]
@thunderstorm010 It still gets replaced for me. With the same message:
![image](https://user-images.githubusercontent.com/62779748/188496780-3c42d5ab-4c84-4fac-8a18-6bef18428a53.png)

EDIT:
I added your modified version of 0BDFDB lib, and now it does not get replaced on load and ShowHiddenChannels works again, but it breaks a lot of others add-ons:

Character counter colour was not black before, and now it is:
![image](https://user-images.githubusercontent.com/62779748/188497078-e63abbdf-270b-442e-9d94-4a855491c7d9.png)

Notifications are now at the bottom and spans the hole length and is black on dark grey. Basically fully broken:
![image](https://user-images.githubusercontent.com/62779748/188497479-68d70f21-6186-4846-9451-10b546f5a5e5.png)

This is why I have HIGHLY recommended in my last post that you fork the 0BDFDB library and change its name so that both real 0BDFDB and your modified 0BDFDB can live together. Also, I recommended you modify the metadata of ShowHiddenChannels enough that the real 0BDFDB won't delete your modified version of ShowHiddenChannels and replace it with the useless version.

**Comment by mutageneral** [comment]
New bug with using your version of 0BDFDB found:
![image](https://user-images.githubusercontent.com/62779748/188498798-bf625134-9ec1-4e17-9857-55eb64ce13bd.png)

**Comment by mutageneral** [comment]
Should we move the issue of 0BDFDB breaking everything to a new issue? @thunderstorm010

**Comment by xAstroBoy** [comment]
He's not anymore the maintainer, and to fix this issue yall have to replace 0BDFD8 with the files here

**Comment by teisseire117** [comment]
> He's not anymore the maintainer, and to fix this issue yall have to replace 0BDFD8 with the files here

I did. Same issue.

It's not the same issue as the one in the Original Post.
It's a new issue. Go to Plugin Repo you'll see the issue.
It also causes an issue with some text turning black 
![cHSIJVw](https://user-images.githubusercontent.com/43145883/188501895-5079ed87-8406-428e-a224-2def0875e2f7.png)

This black text is generated by other Devilbro's plug-ins : CreationDate, JoinedAtDate, and LastMessageData

PluginRepo is also a Devilbro's plug-in.

And it's possible that the issues with them is caused by your version of 0BDFD8. For which @mutageneral proposed a work-around

**Comment by thunderstorm010** [comment]
Simple solution I suggest: Switch to Replugged. I realized that BD is shit.

**Comment by xAstroBoy** [comment]
Agreed, im doing the switch as well

**Comment by teisseire117** [comment]
hahaha, shit. I guess I'll take a loot at it. BD had a lot of plugins, that's what made it interesting

**Comment by xAstroBoy** [comment]
> hahaha, shit. I guess I'll take a loot at it. BD had a lot of plugins, that's what made it interesting

There's BDCompat for replugged, that will get any BD plugin work with it

**Comment by teisseire117** [comment]
> > hahaha, shit. I guess I'll take a loot at it. BD had a lot of plugins, that's what made it interesting
> 
> There's BDCompat for replugged, that will get any BD plugin work with it

I guess all but ShowHiddenChannels

**Comment by xAstroBoy** [comment]
> > > hahaha, shit. I guess I'll take a loot at it. BD had a lot of plugins, that's what made it interesting
> > 
> > 
> > There's BDCompat for replugged, that will get any BD plugin work with it
> 
> I guess all but ShowHiddenChannels since it requires this modified version of 0BDFDB which itself makes some text go black, and we're just at the same point

https://github.com/discord-modifications/show-hidden-channels

**Comment by teisseire117** [comment]
> > > > hahaha, shit. I guess I'll take a loot at it. BD had a lot of plugins, that's what made it interesting
> > > 
> > > 
> > > There's BDCompat for replugged, that will get any BD plugin work with it
> > 
> > 
> > I guess all but ShowHiddenChannels since it requires this modified version of 0BDFDB which itself makes some text go black, and we're just at the same point
> 
> https://github.com/discord-modifications/show-hidden-channels

that's amazing !

**Comment by teisseire117** [comment]
Quite expected, BDCompat is making Discord freeze on startup, probably one of the plug-ins causing that. Along other issues.
I'll go back to BD and try fixing the Show Hidden Channels myself I guess

**Comment by xAstroBoy** [comment]
> Quite expected, BDCompat is making Discord freeze on startup, probably one of the plug-ins causing that. Along other issues. I'll go back to BD and try fixing the Show Hidden Channels myself I guess

use this https://github.com/Juby210/bdCompat and remove any of devilbro's trash

**Comment by mutageneral** [comment]
Hey @teisseire117
I'm now using @Saalvage fork of the ShowHiddenChannels add-on on BetterDiscord. It does not require its own version of 0BDFDB and all add-ons that use it works flawlessly.
Here is the link: https://github.com/Saalvage/BetterDiscordAddons
